# Generated by Django 4.2.3 on 2023-07-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='note',
            new_name='Page',
        ),
    ]
